[[customizations.user]]
groups = ["wheel", "root"]
name = "peerpod"
password = "peerpod"

[[customizations.filesystem]]
mountpoint = "/"
minsize = "5 GiB"

[[customizations.filesystem]]
mountpoint = "/var/kata-containers"
minsize = "35 GiB"
