apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-sandboxed-containers-operator
  namespace: openshift-sandboxed-containers-operator
spec:
  channel: stable
  installPlanApproval: Manual
  name: sandboxed-containers-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # This is tied to the CoCo on baremetal preview release
  # We use the current GA release subscription as BM releases happens
  # post the GA of the CoCO/peer-pods releases for now
  startingCSV: sandboxed-containers-operator.v1.9.0
