apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: "openshift-sandboxed-containers-operator"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 120
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 120
        - effect: NoSchedule
          key: node.kubernetes.io/memory-pressure
          operator: Exists
      volumes:
        - name: ssh
          secret:
            defaultMode: 384
            optional: true
            secretName: ssh-key-secret
      containers:
        - command:
            - /manager
          args:
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          volumeMounts:
            - mountPath: /root/.ssh/
              name: ssh
              readOnly: true
          envFrom:
            - secretRef:
                name: peer-pods-secret
                optional: true
            - configMapRef:
                name: peer-pods-cm
                optional: true
          image: controller:latest
          name: manager
          env:
            - name: PEERPODS_NAMESPACE
              value: "openshift-sandboxed-containers-operator"
            - name: RELATED_IMAGE_KATA_MONITOR
              value: registry.redhat.io/openshift-sandboxed-containers/osc-monitor-rhel9@sha256:62ec43183c77ada292c893e4af77d2a071026ed02d58f032077d4fa7bc7017a1
            - name: RELATED_IMAGE_CAA
              value: registry.redhat.io/openshift-sandboxed-containers/osc-cloud-api-adaptor-rhel9@sha256:31f04825d37a8821616642573987abe9feb97017f299eee3a95745797c623667
            - name: RELATED_IMAGE_PEERPODS_WEBHOOK
              value: registry.redhat.io/openshift-sandboxed-containers/osc-cloud-api-adaptor-webhook-rhel9@sha256:abfbd658b8fa83492420ff276fe369388898a828ba18e060f33d13e54ae4353f
            - name: RELATED_IMAGE_PODVM_BUILDER
              value: registry.redhat.io/openshift-sandboxed-containers/osc-podvm-builder-rhel9@sha256:9d0ef07344f2c8360a1a12d196661b058d38452ba61f2a813f79b5a98c30c819
            - name: RELATED_IMAGE_PODVM_PAYLOAD
              value: registry.redhat.io/openshift-sandboxed-containers/osc-podvm-payload-rhel9@sha256:925ccddf23ba2a12a1c8ec86d3a678f28e4a868441b28aa0e3932cc6d4caccaa 
            - name: RELATED_IMAGE_PODVM_OCI
              value: ""
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 40Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      terminationGracePeriodSeconds: 10
