apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: "openshift-sandboxed-containers-operator"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 120
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 120
        - effect: NoSchedule
          key: node.kubernetes.io/memory-pressure
          operator: Exists
      volumes:
        - name: ssh
          secret:
            defaultMode: 384
            optional: true
            secretName: ssh-key-secret
      containers:
        - command:
            - /manager
          args:
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          volumeMounts:
            - mountPath: /root/.ssh/
              name: ssh
              readOnly: true
          envFrom:
            - secretRef:
                name: peer-pods-secret
                optional: true
            - configMapRef:
                name: peer-pods-cm
                optional: true
          image: controller:latest
          name: manager
          env:
            - name: PEERPODS_NAMESPACE
              value: "openshift-sandboxed-containers-operator"
            - name: RELATED_IMAGE_KATA_MONITOR
              value: registry.redhat.io/openshift-sandboxed-containers/osc-monitor-rhel9@sha256:54e0b3ed94bb414ea759c5ecf02d29fd8dffa4cd746ebddc3138c8383bdeadb0
            - name: RELATED_IMAGE_CAA
              value: registry.redhat.io/openshift-sandboxed-containers/osc-cloud-api-adaptor-rhel9@sha256:f501d9750de60cea7582c9a4cdd9f90e381eb4a0e2119b7be31983e78f085c35
            - name: RELATED_IMAGE_PEERPODS_WEBHOOK
              value: registry.redhat.io/openshift-sandboxed-containers/osc-cloud-api-adaptor-webhook-rhel9@sha256:66467aa75180267bddbe8daad18a23e9e26f7104f1c0ecaff22acbe641fb6fc1
            - name: RELATED_IMAGE_PODVM_BUILDER
              value: registry.redhat.io/openshift-sandboxed-containers/osc-podvm-builder-rhel9@sha256:fec854750f7c5e137d0f77d2069e8a8cb66b17d6e4fc8f8eec2df22b56b2772e
            - name: RELATED_IMAGE_PODVM_PAYLOAD
              value: registry.redhat.io/openshift-sandboxed-containers/osc-podvm-payload-rhel9@sha256:596be40dd2149673d03f8b83eba642f391e7abf70d65974e431a33e63d698386 
            - name: RELATED_IMAGE_PODVM_OCI
              value: ""
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 40Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      terminationGracePeriodSeconds: 10
