apiVersion: batch/v1
kind: Job
metadata:
  name: osc-podvm-gallery-deletion
  namespace: openshift-sandboxed-containers-operator
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 1
  template:
    metadata:
      name: osc-podvm-gallery-deletion
    spec:
      containers:
        - name: delete-gallery
          image: registry.redhat.io/openshift-sandboxed-containers/osc-podvm-builder-rhel9:1.8.1  ## OSC_VERSION
          securityContext:
            runAsUser: 0 # needed for container mode dnf access
          envFrom:
            - secretRef:
                name: peer-pods-secret
            - configMapRef:
                name: peer-pods-cm
                optional: true
            - configMapRef:
                name: azure-podvm-image-cm
                optional: true
            - configMapRef:
                name: aws-podvm-image-cm
                optional: true
          command: ["/podvm-builder.sh", "delete-gallery", "-f"]

      restartPolicy: Never
