apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/sandboxed-containers-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression:
      event == "push" &&
      target_branch == "devel" &&
      files.all.exists(path, path.matches('.tekton/fbc-pipeline.yaml$|.tekton/osc-fbc-4-16-.*.yaml$|fbc/v4.16/Dockerfile$|fbc/v4.16/.*/catalog.json$'))
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: osc-fbc-4-16
    appstudio.openshift.io/component: osc-fbc-4-16
    pipelines.appstudio.openshift.io/type: build
  name: osc-fbc-4-16-on-push
  namespace: ose-osc-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ose-osc-tenant/osc-fbc-4-16:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/s390x
  - name: path-context
    value: fbc/v4.16
  - name: dockerfile
    value: fbc/v4.16/Dockerfile
  pipelineRef:
    params:
    - name: name
      value: fbc-builder
    - name: bundle
      value: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder:devel@sha256:2461be756815249c623ad7f99607371970f0f926927c1573e1114d33e3854c2c
    - name: kind
      value: pipeline
    resolver: bundles
  taskRunTemplate: {}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
