name: Build Bootc PodVM Image

on:
  push:
    branches: [ devel ]
    paths:
      - 'config/peerpods/podvm/bootc/**'
  pull_request:
    branches: [ devel ]
    paths:
      - 'config/peerpods/podvm/bootc/**'
  workflow_dispatch:
    inputs:
      cloud_provider:
        description: 'Cloud provider (azure, aws, libvirt)'
        required: true
        default: 'azure'
        type: choice
        options:
          - azure
          - aws
          - libvirt
      build_disk:
        description: 'Build disk image from container'
        required: false
        default: true
        type: boolean
      build_target:
        description: 'Container target to build'
        required: false
        default: 'nvidia-podvm-bootc'
        type: choice
        options:
          - podvm-bootc
          - nvidia-podvm-bootc

env:
  CLOUD_PROVIDER: ${{ github.event.inputs.cloud_provider || 'azure' }}

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout repository  
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine build target
        id: target
        run: |
          # Default to nvidia, use standard only when explicitly requested
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.build_target }}" ]]; then
            echo "BUILD_TARGET=${{ github.event.inputs.build_target }}" >> $GITHUB_OUTPUT
            echo "IMAGE_TAG=${{ github.event.inputs.build_target }}:${{ github.sha }}" >> $GITHUB_OUTPUT
          else # default to nvidia-podvm-bootc
            echo "BUILD_TARGET=nvidia-podvm-bootc" >> $GITHUB_OUTPUT
            echo "IMAGE_TAG=podvm-bootc-nvidia:${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Build bootc container image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: config/peerpods/podvm/bootc
          file: config/peerpods/podvm/bootc/Containerfile.fedora
          target: ${{ steps.target.outputs.BUILD_TARGET }}
          build-args: |
            CLOUD_PROVIDER=${{ env.CLOUD_PROVIDER }}
          tags: ${{ steps.target.outputs.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          load: true

      - name: Set up skopeo
        uses: warjiang/setup-skopeo@main
        with:
          version: latest

      - name: Skopeo copy bootc container image to podman
        run: |
          sudo skopeo copy docker-daemon:${{ steps.target.outputs.IMAGE_TAG }} containers-storage:${{ steps.target.outputs.IMAGE_TAG }}

      - name: list images in sudo podman
        run: sudo podman images

      - name: Create output directory
        working-directory: config/peerpods/podvm/bootc
        run: |
          mkdir -p output/qcow2

#TODO config.toml

      - name: Build disk image
        working-directory: config/peerpods/podvm/bootc
        run: |
          echo "Building disk image..."
          sudo podman run \
            --rm \
            --privileged \
            --security-opt label=type:unconfined_t \
            -v $(pwd)/config.toml:/config.toml:ro \
            -v $(pwd)/output:/output \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type qcow2 \
            --rootfs xfs \
            --local \
            ${{ steps.target.outputs.IMAGE_TAG }}

      - name: Verify disk image exists
        working-directory: config/peerpods/podvm/bootc
        run: ls -lh ${{ github.workspace }}/config/peerpods/podvm/bootc/output/qcow2/disk.qcow2 

      - name: Wrap disk in oci image
        uses: docker/build-push-action@v6
        with:
          context: config/peerpods/podvm
          file: config/peerpods/podvm/Dockerfile.podvm-oci
          tags: ${{ steps.target.outputs.IMAGE_TAG }}-oci
          build-args: PODVM_IMAGE_SRC=bootc/output/qcow2/disk.qcow2
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          load: true