name: Build Bootc PodVM Image

on:
  push:
    branches: [ devel ]
    paths:
      - 'config/peerpods/podvm/bootc/**'
  pull_request:
    branches: [ devel ]
    paths:
      - 'config/peerpods/podvm/bootc/**'
  workflow_dispatch:
    inputs:
      cloud_provider:
        description: 'Cloud provider (azure, aws, libvirt)'
        required: true
        default: 'azure'
        type: choice
        options:
          - azure
          - aws
          - libvirt

      build_disk:
        description: 'Build disk image from container'
        required: false
        default: true
        type: boolean
      container_variant:
        description: 'Container variant to convert to disk (standard or nvidia)'
        required: false
        default: 'standard'
        type: choice
        options:
          - standard
          - nvidia

env:
  CLOUD_PROVIDER: ${{ github.event.inputs.cloud_provider || 'azure' }}

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: config/peerpods/podvm/bootc
          file: config/peerpods/podvm/bootc/Containerfile.fedora
          target: default-target
          build-args: |
            CLOUD_PROVIDER=${{ env.CLOUD_PROVIDER }}
          tags: podvm-bootc:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          outputs: type=docker,dest=/tmp/podvm-bootc.tar

      - name: Upload container image artifact
        uses: actions/upload-artifact@v4
        with:
          name: podvm-bootc-container-${{ github.sha }}
          path: /tmp/podvm-bootc.tar
          retention-days: 7



  build-nvidia-container:
    runs-on: ubuntu-latest
    if: github.event.inputs.cloud_provider == 'azure' || github.event_name != 'workflow_dispatch'
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build NVIDIA container image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: config/peerpods/podvm/bootc
          file: config/peerpods/podvm/bootc/Containerfile.fedora
          target: nvidia-podvm-bootc
          build-args: |
            CLOUD_PROVIDER=${{ env.CLOUD_PROVIDER }}
          tags: podvm-bootc-nvidia:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          outputs: type=docker,dest=/tmp/podvm-bootc-nvidia.tar

      - name: Upload NVIDIA container image artifact
        uses: actions/upload-artifact@v4
        with:
          name: podvm-bootc-nvidia-container-${{ github.sha }}
          path: /tmp/podvm-bootc-nvidia.tar
          retention-days: 7

  build-disk-image:
    runs-on: ubuntu-latest
    needs: [build-container, build-nvidia-container]
    if: github.event_name != 'pull_request' && (github.event.inputs.build_disk != 'false') && (always() && !cancelled() && !failure())
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine container variant
        run: |
          VARIANT="${{ github.event.inputs.container_variant || 'standard' }}"
          echo "CONTAINER_VARIANT=$VARIANT" >> $GITHUB_ENV

          if [ "$VARIANT" = "nvidia" ]; then
            echo "ARTIFACT_NAME=podvm-bootc-nvidia-container-${{ github.sha }}" >> $GITHUB_ENV
            echo "CONTAINER_FILE=podvm-bootc-nvidia.tar" >> $GITHUB_ENV
          else
            echo "ARTIFACT_NAME=podvm-bootc-container-${{ github.sha }}" >> $GITHUB_ENV
            echo "CONTAINER_FILE=podvm-bootc.tar" >> $GITHUB_ENV
          fi

      - name: Download container image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: /tmp

      - name: Load container image
        run: |
          # Load the container image from the artifact
          echo "Loading container from: /tmp/${{ env.CONTAINER_FILE }}"
          docker load -i /tmp/${{ env.CONTAINER_FILE }}

          # Get the loaded image name and tag
          IMAGE_NAME=$(docker images --format "table {{.Repository}}:{{.Tag}}" | grep -v REPOSITORY | head -n1)
          echo "Loaded image: $IMAGE_NAME (variant: ${{ env.CONTAINER_VARIANT }})"
          echo "LOADED_IMAGE=$IMAGE_NAME" >> $GITHUB_ENV

          # Transfer image from Docker to Podman storage for bootc-image-builder
          echo "Transferring image to Podman storage..."
          docker save "$IMAGE_NAME" | sudo podman load

          # Verify image is available in Podman
          sudo podman images | grep -E "(REPOSITORY|$(echo $IMAGE_NAME | cut -d: -f1))"

      - name: Create output directory
        run: |
          mkdir -p output
          sudo chown -R $(id -u):$(id -g) output

      - name: Convert container to disk image
        run: |
          echo "Converting container image: $LOADED_IMAGE"

          # Convert bootc container to qcow2 disk image using the loaded image
          sudo podman run \
            --rm \
            --privileged \
            --security-opt label=type:unconfined_t \
            -v $(pwd)/config/peerpods/podvm/bootc/config.toml:/config.toml:ro \
            -v $(pwd)/output:/output \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type qcow2 \
            --rootfs xfs \
            --use-librepo=True \
            "$LOADED_IMAGE"

      - name: Compress disk image
        run: |
          cd output/qcow2
          if [ -f disk.qcow2 ]; then
            echo "Compressing disk image..."
            xz -9 -T 0 disk.qcow2
            ls -lah disk.qcow2.xz
          else
            echo "Error: disk.qcow2 not found"
            ls -la
            exit 1
          fi

      - name: Upload disk image artifact
        uses: actions/upload-artifact@v4
        with:
          name: podvm-disk-${{ env.CONTAINER_VARIANT }}-${{ env.CLOUD_PROVIDER }}-${{ github.sha }}
          path: output/qcow2/disk.qcow2.xz
          retention-days: 30

      - name: Generate disk image metadata
        run: |
          cd output/qcow2
          if [ -f disk.qcow2.xz ]; then
            echo "DISK_SIZE=$(stat -c%s disk.qcow2.xz)" >> $GITHUB_ENV
            echo "DISK_SHA256=$(sha256sum disk.qcow2.xz | cut -d' ' -f1)" >> $GITHUB_ENV
          fi

      - name: Create release info
        if: github.ref == 'refs/heads/devel'
        run: |
          cat > disk-info.json << EOF
          {
            "cloud_provider": "${{ env.CLOUD_PROVIDER }}",
            "container_variant": "${{ env.CONTAINER_VARIANT }}",
            "container_image": "${{ env.LOADED_IMAGE }}",
            "disk_size_bytes": "${{ env.DISK_SIZE }}",
            "disk_sha256": "${{ env.DISK_SHA256 }}",
            "build_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "git_commit": "${{ github.sha }}",
            "git_ref": "${{ github.ref }}"
          }
          EOF

      - name: Upload disk metadata
        if: github.ref == 'refs/heads/devel'
        uses: actions/upload-artifact@v4
        with:
          name: podvm-disk-metadata-${{ env.CONTAINER_VARIANT }}-${{ env.CLOUD_PROVIDER }}-${{ github.sha }}
          path: disk-info.json
          retention-days: 90
